config/routes.rb
Crowdhoster::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  # PAGES
  root                                         to: 'pages#index'

  # USERS
  devise_for :users, { path: 'account' }
  devise_scope :user do
    match '/user/settings',                    to: 'devise/registrations#edit',             as: :user_settings
  end

  # ADMIN
  get '/admin',                                to: 'admin#admin_dashboard',                 as: :admin_dashboard
  match '/admin/homepage',                     to: 'admin#admin_homepage',                  as: :admin_homepage
  match '/admin/site-settings',                to: 'admin#admin_site_settings',             as: :admin_site_settings
  match '/admin/customize',                    to: 'admin#admin_customize',                 as: :admin_customize
  namespace :admin do
    resources :campaigns
    post '/payments/:id/refund',               to: 'payments#refund_payment',               as: :admin_payment_refund
  end

  match '/admin/campaigns/:id/copy',           to: 'admin/campaigns#copy',                  as: :admin_campaigns_copy
  match '/admin/campaigns/:id/payments',       to: 'admin/campaigns#payments',              as: :admin_campaigns_payments
  match '/admin/processor-setup',              to: 'admin#admin_processor_setup',           as: :admin_processor_setup
  post '/admin/bank-setup',                    to: 'admin#create_admin_bank_account',       as: :create_admin_bank_account
  get '/admin/bank-setup',                     to: 'admin#admin_bank_account',              as: :admin_bank_account
  delete '/admin/bank-setup',                  to: 'admin#delete_admin_bank_account',       as: :delete_admin_bank_account
  match '/admin/notification-setup',           to: 'admin#admin_notification_setup',        as: :admin_notification_setup
  match '/ajax/verify',                        to: 'admin#ajax_verify',                     as: :ajax_verify

  # CAMPAIGNS
  match '/:id/checkout/amount',                to: 'campaigns#checkout_amount',             as: :checkout_amount
  match '/:id/checkout/payment',               to: 'campaigns#checkout_payment',            as: :checkout_payment
  match '/:id/checkout/process',               to: 'campaigns#checkout_process',            as: :checkout_process
  match '/:id/checkout/confirmation',          to: 'campaigns#checkout_confirmation',       as: :checkout_confirmation
  post '/:id/checkout/error',                  to: 'campaigns#checkout_error',              as: :checkout_error
  match '/:id',                                to: 'campaigns#home',                        as: :campaign_home
  match '/:id/ajax/create_payment_user',       to: 'campaigns#ajax_create_payment_user',    as: :ajax_create_payment_user
  match '/:id/send_feedback',                to: 'campaigns#send_feedback',               as: :send_feedback

  namespace :api, defaults: {format: 'json'} do
    scope module: :v0  do
      resources :campaigns, only: :show do
        resources :payments, only: :index
      end
    end
  end
end

app/controllers/admin/campaigns_controller.rb
class Admin::CampaignsController < ApplicationController
  include AdminMixin
  layout "admin"
  before_filter :authenticate_user!
  before_filter :verify_admin
  before_filter { |c| c.create_breadcrumb ['Campaigns', admin_campaigns_path] }

  def index
    @campaigns = Campaign.order("created_at ASC")
  end

  def new
    @campaign = Campaign.new
    create_breadcrumb(['New Campaign', new_admin_campaign_path])
  end

  def copy
    old_campaign = Campaign.find(params[:id])
    @campaign = old_campaign.dup
    @campaign.expiration_date = Time.now + 30.days
    @campaign.published_flag = false
    @campaign.production_flag = false

    begin
      campaign = {
        title: @campaign.name,
        tilt_amount: @campaign.goal_dollars*100,
        expiration_date: @campaign.expiration_date,
        user_id: @settings.ct_sandbox_admin_id,
        billing_statement_text: @settings.billing_statement_text
      }
      #Crowdtilt.sandbox
      #response = Crowdtilt.post('/campaigns', {campaign: campaign})
    rescue => exception
      redirect_to admin_campaigns, :flash => { :error => "Could not copy campaign" }
    else
      #@campaign.update_api_data(response['campaign'])
      @campaign.save
    end

    # Completely refresh the FAQs
    old_campaign.faqs.each do |faq|
      @campaign.faqs.create question: faq.question, answer: faq.answer
    end

    # Completely refresh the rewards
    old_campaign.rewards.each do |reward|
      @campaign.rewards.create title: reward.title,
                               image_url: reward.image_url,
                               description: reward.description,
                               delivery_date: reward.delivery_date,
                               number: reward.number,
                               price: reward.price,
                               collect_shipping_flag: reward.collect_shipping_flag,
                               include_claimed: reward.include_claimed
    end

    render action: "edit"
  end

  def create
    is_default = params[:campaign].delete :is_default
    @campaign = Campaign.new(params[:campaign])

    if !@campaign.valid?
      flash.now[:error] = @campaign.errors.full_messages.join(', ')
      render action: "new"
      return
    end

     # Set the campaign user id
     ct_user_id = @campaign.production_flag ? @settings.ct_production_admin_id : @settings.ct_sandbox_admin_id

    # calculate the goal amount (in case of a tilt by orders campaign)
    @campaign.set_goal

    # Create a corresponding campaign on the Crowdtilt API
    # If it fails, echo the error message sent by the API back to the user
    # If successful, save the campaign
    begin
      campaign = {
        title: @campaign.name,
        tilt_amount: (@campaign.goal_dollars*100).to_i,
        expiration_date: @campaign.expiration_date,
        user_id: ct_user_id,
        billing_statement_text: @settings.billing_statement_text
      }
      #@campaign.production_flag ? Crowdtilt.production(@settings) : Crowdtilt.sandbox
      #response = Crowdtilt.post('/campaigns', {campaign: campaign})
    rescue => exception
      flash.now[:error] = exception.to_s
      render action: "new"
      return
    else
      #@campaign.update_api_data(response['campaign'])
      @campaign.save

      # Now that we've created the campaign, create new FAQs if any were provided
      if params.has_key?(:faq)
        params[:faq].each do |faq|
          if !faq['question'].empty?
            @campaign.faqs.create question: faq['question'], answer: faq['answer']
          end
        end
      end

      # Now that we've created the campaign, create new Reward Levels if any were provided
      if params.has_key?(:reward)
        params[:reward].each do |reward|
          unless reward['delete'] && reward['delete'] == 'delete'
              @campaign.rewards.create title: reward['title'],
                                       image_url: reward['image_url'],
                                       description: reward['description'],
                                       delivery_date: reward['delivery_date'],
                                       number: reward['number'].to_i,
                                       price: reward['price'].to_f,
                                       collect_shipping_flag: reward['collect_shipping_flag'],
                                       include_claimed: reward['include_claimed']
          end
        end
      end

      # Check again for campaign validity now that we've added faqs and rewards
      if !@campaign.valid?
        flash.now[:error] = @campaign.errors.full_messages.join(', ')
        render action: "new"
        return
      end

      # Set default campaign
      if(is_default == "1")
        @settings.default_campaign_id = @campaign.id
      elsif (@settings.default_campaign_id == @campaign.id)
        @settings.default_campaign_id = nil
      end
      @settings.save

      redirect_to campaign_home_url(@campaign, :sr => current_user.sr), :flash => { :success => "Campaign created!" }
      return
    end
  end

  def edit
    @campaign = Campaign.find(params[:id])
    create_breadcrumb(['Edit Campaign', edit_admin_campaign_path(@campaign)])
  end

  def update
    @campaign = Campaign.find(params[:id])

    is_default = params[:campaign].delete :is_default

    if(is_default =="1")
      @settings.default_campaign_id = @campaign.id
    elsif (@settings.default_campaign_id == @campaign.id)
      @settings.default_campaign_id = nil
    end
    @settings.save

    # We don't immediately update the campaign, becuase the Crowdtilt API may still fail a validation
    @campaign.assign_attributes(params[:campaign])

    # Completely refresh the FAQ data
    @campaign.faqs.destroy_all
    if params.has_key?(:faq)
      params[:faq].each do |faq|
        if !faq['question'].empty?
          @campaign.faqs.create question: faq['question'], answer: faq['answer']
        end
      end
    end

    # Update the Reward Levels
    if params.has_key?(:reward)
      params[:reward].each do |reward|
        if reward['delete'] && reward['delete'] == 'delete'
          if reward['id']
            r = Reward.find(reward['id'])
            r.destroy if(r.payments.length == 0)
          end
        else
          if reward['id']
              r = Reward.find(reward['id'])
              r.title = reward['title']
              r.image_url = reward['image_url']
              r.description = reward['description']
              r.delivery_date = reward['delivery_date']
              r.number = reward['number'].to_i
              r.price = reward['price'].to_f
              r.collect_shipping_flag = reward['collect_shipping_flag']
              r.include_claimed = reward['include_claimed']
              unless r.save
                flash.now[:error] = "A reward field is missing or invalid"
                render action: "edit"
                return
              end
          else
            @campaign.rewards.create title: reward['title'],
                                     image_url: reward['image_url'],
                                     description: reward['description'],
                                     delivery_date: reward['delivery_date'],
                                     number: reward['number'].to_i,
                                     price: reward['price'].to_f,
                                     collect_shipping_flag: reward['collect_shipping_flag'],
                                     include_claimed: reward['include_claimed']
          end
        end
      end
    end

    if !@campaign.valid?
      flash.now[:error] = @campaign.errors.full_messages.join(', ')
      render action: "edit"
      return
    end

    # Set the campaign user id
     ct_user_id = @campaign.production_flag ? @settings.ct_production_admin_id : @settings.ct_sandbox_admin_id

    #if campaign has been promoted to production, delete all sandbox payments
    if @campaign.production_flag && @campaign.production_flag_changed?
      @campaign.payments.destroy_all
    end

    # calculate the goal amount (in case of a tilt by orders campaign)
    @campaign.set_goal
    logger.info "LOG STMT 1"
    # Update the corresponding campaign on the Crowdtilt API
    # If it fails, echo the error message sent by the API back to the user
    # If successful, save the campaign
    begin
      campaign = {
        title: @campaign.name,
        tilt_amount: (@campaign.goal_dollars*100).to_i,
        expiration_date: @campaign.expiration_date,
        billing_statement_text: @settings.billing_statement_text
      }
      logger.info "LOG STMT 2"
      # If the campaign has been promoted to production, create a new campaign on the Crowtilt API
      #if @campaign.production_flag && @campaign.production_flag_changed?
       # campaign[:user_id] = ct_user_id
        #Crowdtilt.production(@settings)
        #response = Crowdtilt.post('/campaigns', {campaign: campaign})
      #else
       # @campaign.production_flag ? Crowdtilt.production(@settings) : Crowdtilt.sandbox
       # response = Crowdtilt.put('/campaigns/' + @campaign.ct_campaign_id, {campaign: campaign})
      #end
    rescue => exception
      flash.now[:error] = exception.to_s
      render action: "edit" and return
    else
      #@campaign.update_api_data(response['campaign'])
      @campaign.save
      redirect_to campaign_home_url(@campaign), :flash => { :success => "Campaign updated!" } and return
    end
  end

  def payments
#     @campaign = Campaign.find(params[:id])
#     page = params[:page] || 1
#
#     #Check if the user is searching for a certain payment_id
#     if params.has_key?(:payment_id) && !params[:payment_id].blank?
#       begin
#         response = Crowdtilt.get('/campaigns/' + @campaign.ct_campaign_id + '/payments/' + params[:payment_id])
#       rescue => exception
#         #This means the payment_id wasn't found, so go ahead and grab all payments

app/controllers/api/v0/campaigns_controller.rb
class Api::V0::CampaignsController < Api::V0::BaseController
  def show
    render json: Campaign.find(params[:id])
  end
end

app/helpers/admin/campaigns_helper.rb
module Admin::CampaignsHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper

  def short_price(price, currency_symbol='', precision=nil)
    precision ||= (price*100%100==0.0 ? 0 : 2)
    "#{currency_symbol}#{number_with_precision(price, delimiter: ",", precision: precision)}"
  end
end

app/views/admin/campaigns/edit.html.erb
<div id="admin">
  <div class="container content_box clearfix">

  <%= render 'admin/header', active: 'campaigns' %>

  <div id="admin_campaigns">
    <%= render 'form' %>
  </div>
  </div>
</div>

app/views/admin/campaigns/index.html.erb
<div id="admin">
  <div class="container content_box clearfix">

  <%= render 'admin/header', active: 'campaigns' %>

    <div id="admin_campaigns">

      <table class="table table-striped">
        <tr>
          <th>Name</th>
          <th>Goal</th>
          <th>Raised</th>
          <th>Expiration<br/>Date</th>
          <th>Published?</th>
          <th>Payments<br/>Activated?</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>

      <% @campaigns.each do |campaign| %>
        <tr>
          <td><%= campaign.name %></td>

          <td>
            <% if campaign.goal_type == "dollars" %>
              <%= short_price(campaign.goal_dollars.to_f, '$', 2) %>
            <% else %>
              <%= campaign.goal_orders %>
            <% end %>
          </td>
          <td>
            <% if campaign.goal_type == "dollars" %>
              <%= short_price(campaign.stats_raised_amount.to_f, '$', 2) %>
            <% else %>
              <%= campaign.orders %>
            <% end %>
          </td>

          <td><%= Date.parse(campaign.expiration_date.to_s).strftime("%m/%d/%Y") %></td>
          <td><%= campaign.published_flag ? raw('<i class="icon-ok"></i>') : '' %></td>
          <td><%= campaign.production_flag ? raw('<i class="icon-ok"></i>') : '' %></td>
          <td><%= link_to 'Edit', edit_admin_campaign_path(campaign) %></td>
          <td><%= link_to 'View', campaign_home_path(campaign) %></td>
          <td><%= link_to 'Payments', admin_campaigns_payments_path(campaign) %></td>
          <td><%= link_to 'Copy', admin_campaigns_copy_path(campaign) %></td>
        </tr>
      <% end %>
      </table>

      <br />

      <%= link_to 'New Campaign', new_admin_campaign_path %>
    </div>
  </div>
</div>

<% if flash[:signup_modal] %>
<div class="modal hide fade" id="signupModal">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Your page is almost ready!</h3>
  </div>
  <div class="modal-body">
    <p>Start out by creating your first campaign.</p>
    <p>If you have any questions as you get started, reach out to us: <a href="mailto:support@altheahealth.com?subject=I%20have%20questions%20about%20getting%20started%20with%20Crowdtilt%20Open">support@altheahealth.com</a>.</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
    <a href="<%= new_admin_campaign_path %>" class="btn btn-primary">Start campaign!</a>
  </div>
</div>

<% content_for :scripts do %>
<script type="text/javascript">
    $(window).load(function(){
        $('#signupModal').modal('show');
    });
</script>
<% end %>

<% end %>

app/views/admin/campaigns/new.html.erb
<div id="admin">
  <div class="container content_box clearfix">

  <%= render 'admin/header', active: 'campaigns' %>

  <div id="admin_campaigns">
    <%= render 'form' %>
  </div>
  </div>
</div>

app/views/admin/campaigns/payments.html.erb
<div id="admin">
  <div class="container content_box clearfix">

  <%= render 'admin/header', active: 'campaigns' %>

  <div id="admin_payments">
    <h4><%= @campaign.name %></h4>

    <% if @payments.count > 0 %>
      <br />

      <div class="search id">
        <form accept-charset="UTF-8" action="<%= admin_campaigns_payments_path(@campaign) %>" method="get">

          <input id="payment_id" type="text" name="payment_id" placeholder="Search by Payment ID" value="<%= params[:payment_id] if params.has_key?(:payment_id) %>"/>
          <button type="submit" class="btn btn-primary show_loader" data-loader="admin_header">Search</button>
        <% if params.has_key?(:payment_id) %>
          <%= link_to "clear", admin_campaigns_payments_path(@campaign), :class => 'show_loader', :'data-loader' => "admin_header" %>
        <% end %>

        </form>
      </div>
      <div class="search email">
        <form accept-charset="UTF-8" action="<%= admin_campaigns_payments_path(@campaign) %>" method="get">

          <input id="payment_id" type="text" name="email" placeholder="Search by email" value="<%= params[:email] if params.has_key?(:email) %>"/>
          <button type="submit" class="btn btn-primary show_loader" data-loader="admin_header">Search</button>
        <% if params.has_key?(:email) %>
          <%= link_to "clear", admin_campaigns_payments_path(@campaign), :class => 'show_loader', :'data-loader' => "admin_header" %>
        <% end %>

        </form>
      </div>

      <a href="<%= admin_campaigns_payments_path(format: "csv") %>" class="pull-right">
        <button type="button" class="btn btn-default">
          <i class="icon-download"></i> Download CSV
        </button>
      </a>

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <% if @campaign.goal_type == 'orders' %>
            <th>Quantity</th>
            <% end %>
            <th>Sponsor Reference</th>
            <th>Amount</th>
            <th>User Fee</th>
            <th>Date</th>
            <th>Status</th>
            <th>Payment ID</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @payments.each do |payment| %>
          <tr>
            <td><%= payment.fullname %></td>
            <td class="email"><%= payment.email %></td>
            <% if @campaign.goal_type == 'orders' %>
            <td><%= payment.quantity %></td>
            <% end %>
            <td class="sponsor_reference"><%= payment.sponsor_reference %></td>
            <td class="amount"><%= short_price(payment.amount.to_f/100.0, '$', 2) %></td>
            <td class="user_fee_amount"><%= short_price(payment.user_fee_amount.to_f/100.0, '$', 2) %></td>
            <td><%= payment.created_at.strftime("%m/%d/%Y") %></td>
            <td class="status"><%= payment.status %></td>
            <td class="ct_payment_id"><%= payment.ct_payment_id %></td>
            <td><% if ['authorized', 'charged'].include? payment.status %><a class="refund-payment" style="cursor: pointer">Refund</a><% end %></td>
            <td style="width: 18px"><span class="loader" style="display: none"></span></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <%# if @total_pages > 1 %>
        <%#= render 'shared/paginate', path: :admin_campaigns_contributors_path, object: @campaign, page: @page, total_pages: @total_pages %>
      <%# end %>
    <% else %>
      <p>No payments yet!</p>
    <% end %>

  </div>
  </div>
</div>