config/routes.rb
Crowdhoster::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  # PAGES
  root                                         to: 'pages#index'

  # USERS
  devise_for :users, { path: 'account' }
  devise_scope :user do
    match '/user/settings',                    to: 'devise/registrations#edit',             as: :user_settings
  end

  # ADMIN
  get '/admin',                                to: 'admin#admin_dashboard',                 as: :admin_dashboard
  match '/admin/homepage',                     to: 'admin#admin_homepage',                  as: :admin_homepage
  match '/admin/site-settings',                to: 'admin#admin_site_settings',             as: :admin_site_settings
  match '/admin/customize',                    to: 'admin#admin_customize',                 as: :admin_customize
  namespace :admin do
    resources :campaigns
    post '/payments/:id/refund',               to: 'payments#refund_payment',               as: :admin_payment_refund
  end

  match '/admin/campaigns/:id/copy',           to: 'admin/campaigns#copy',                  as: :admin_campaigns_copy
  match '/admin/campaigns/:id/payments',       to: 'admin/campaigns#payments',              as: :admin_campaigns_payments
  match '/admin/processor-setup',              to: 'admin#admin_processor_setup',           as: :admin_processor_setup
  post '/admin/bank-setup',                    to: 'admin#create_admin_bank_account',       as: :create_admin_bank_account
  get '/admin/bank-setup',                     to: 'admin#admin_bank_account',              as: :admin_bank_account
  delete '/admin/bank-setup',                  to: 'admin#delete_admin_bank_account',       as: :delete_admin_bank_account
  match '/admin/notification-setup',           to: 'admin#admin_notification_setup',        as: :admin_notification_setup
  match '/ajax/verify',                        to: 'admin#ajax_verify',                     as: :ajax_verify

  # CAMPAIGNS
  match '/:id/checkout/amount',                to: 'campaigns#checkout_amount',             as: :checkout_amount
  match '/:id/checkout/payment',               to: 'campaigns#checkout_payment',            as: :checkout_payment
  match '/:id/checkout/process',               to: 'campaigns#checkout_process',            as: :checkout_process
  match '/:id/checkout/confirmation',          to: 'campaigns#checkout_confirmation',       as: :checkout_confirmation
  post '/:id/checkout/error',                  to: 'campaigns#checkout_error',              as: :checkout_error
  match '/:id',                                to: 'campaigns#home',                        as: :campaign_home
  match '/:id/ajax/create_payment_user',       to: 'campaigns#ajax_create_payment_user',    as: :ajax_create_payment_user
  match '/:id/send_feedback',                to: 'campaigns#send_feedback',               as: :send_feedback

  namespace :api, defaults: {format: 'json'} do
    scope module: :v0  do
      resources :campaigns, only: :show do
        resources :payments, only: :index
      end
    end
  end
end

app/controllers/admin/campaigns_controller.rb
class Admin::CampaignsController < ApplicationController
  include AdminMixin
  layout "admin"
  before_filter :authenticate_user!
  before_filter :verify_admin
  before_filter { |c| c.create_breadcrumb ['Campaigns', admin_campaigns_path] }

  def index
    @campaigns = Campaign.order("created_at ASC")
  end

  def new
    @campaign = Campaign.new
    create_breadcrumb(['New Campaign', new_admin_campaign_path])
  end

  def copy
    old_campaign = Campaign.find(params[:id])
    @campaign = old_campaign.dup
    @campaign.expiration_date = Time.now + 30.days
    @campaign.published_flag = false
    @campaign.production_flag = false

    begin
      campaign = {
        title: @campaign.name,
        tilt_amount: @campaign.goal_dollars*100,
        expiration_date: @campaign.expiration_date,
        user_id: @settings.ct_sandbox_admin_id,
        billing_statement_text: @settings.billing_statement_text
      }
      #Crowdtilt.sandbox
      #response = Crowdtilt.post('/campaigns', {campaign: campaign})
    rescue => exception
      redirect_to admin_campaigns, :flash => { :error => "Could not copy campaign" }
    else
      #@campaign.update_api_data(response['campaign'])
      @campaign.save
    end

    # Completely refresh the FAQs
    old_campaign.faqs.each do |faq|
      @campaign.faqs.create question: faq.question, answer: faq.answer
    end

    # Completely refresh the rewards
    old_campaign.rewards.each do |reward|
      @campaign.rewards.create title: reward.title,
                               image_url: reward.image_url,
                               description: reward.description,
                               delivery_date: reward.delivery_date,
                               number: reward.number,
                               price: reward.price,
                               collect_shipping_flag: reward.collect_shipping_flag,
                               include_claimed: reward.include_claimed
    end

    render action: "edit"
  end

  def create
    is_default = params[:campaign].delete :is_default
    @campaign = Campaign.new(params[:campaign])

    if !@campaign.valid?
      flash.now[:error] = @campaign.errors.full_messages.join(', ')
      render action: "new"
      return
    end

     # Set the campaign user id
     ct_user_id = @campaign.production_flag ? @settings.ct_production_admin_id : @settings.ct_sandbox_admin_id

    # calculate the goal amount (in case of a tilt by orders campaign)
    @campaign.set_goal

    # Create a corresponding campaign on the Crowdtilt API
    # If it fails, echo the error message sent by the API back to the user
    # If successful, save the campaign
    begin
      campaign = {
        title: @campaign.name,
        tilt_amount: (@campaign.goal_dollars*100).to_i,
        expiration_date: @campaign.expiration_date,
        user_id: ct_user_id,
        billing_statement_text: @settings.billing_statement_text
      }
      #@campaign.production_flag ? Crowdtilt.production(@settings) : Crowdtilt.sandbox
      #response = Crowdtilt.post('/campaigns', {campaign: campaign})
    rescue => exception
      flash.now[:error] = exception.to_s
      render action: "new"
      return
    else
      #@campaign.update_api_data(response['campaign'])
      @campaign.save

      # Now that we've created the campaign, create new FAQs if any were provided
      if params.has_key?(:faq)
        params[:faq].each do |faq|
          if !faq['question'].empty?
            @campaign.faqs.create question: faq['question'], answer: faq['answer']
          end
        end
      end

      # Now that we've created the campaign, create new Reward Levels if any were provided
      if params.has_key?(:reward)
        params[:reward].each do |reward|
          unless reward['delete'] && reward['delete'] == 'delete'
              @campaign.rewards.create title: reward['title'],
                                       image_url: reward['image_url'],
                                       description: reward['description'],
                                       delivery_date: reward['delivery_date'],
                                       number: reward['number'].to_i,
                                       price: reward['price'].to_f,
                                       collect_shipping_flag: reward['collect_shipping_flag'],
                                       include_claimed: reward['include_claimed']
          end
        end
      end

      # Check again for campaign validity now that we've added faqs and rewards
      if !@campaign.valid?
        flash.now[:error] = @campaign.errors.full_messages.join(', ')
        render action: "new"
        return
      end

      # Set default campaign
      if(is_default == "1")
        @settings.default_campaign_id = @campaign.id
      elsif (@settings.default_campaign_id == @campaign.id)
        @settings.default_campaign_id = nil
      end
      @settings.save

      redirect_to campaign_home_url(@campaign, :sr => current_user.sr), :flash => { :success => "Campaign created!" }
      return
    end
  end

  def edit
    @campaign = Campaign.find(params[:id])
    create_breadcrumb(['Edit Campaign', edit_admin_campaign_path(@campaign)])
  end

  def update
    @campaign = Campaign.find(params[:id])

    is_default = params[:campaign].delete :is_default

    if(is_default =="1")
      @settings.default_campaign_id = @campaign.id
    elsif (@settings.default_campaign_id == @campaign.id)
      @settings.default_campaign_id = nil
    end
    @settings.save

    # We don't immediately update the campaign, becuase the Crowdtilt API may still fail a validation
    @campaign.assign_attributes(params[:campaign])

    # Completely refresh the FAQ data
    @campaign.faqs.destroy_all
    if params.has_key?(:faq)
      params[:faq].each do |faq|
        if !faq['question'].empty?
          @campaign.faqs.create question: faq['question'], answer: faq['answer']
        end
      end
    end

    # Update the Reward Levels
    if params.has_key?(:reward)
      params[:reward].each do |reward|
        if reward['delete'] && reward['delete'] == 'delete'
          if reward['id']
            r = Reward.find(reward['id'])
            r.destroy if(r.payments.length == 0)
          end
        else
          if reward['id']
              r = Reward.find(reward['id'])
              r.title = reward['title']
              r.image_url = reward['image_url']
              r.description = reward['description']
              r.delivery_date = reward['delivery_date']
              r.number = reward['number'].to_i
              r.price = reward['price'].to_f
              r.collect_shipping_flag = reward['collect_shipping_flag']
              r.include_claimed = reward['include_claimed']
              unless r.save
                flash.now[:error] = "A reward field is missing or invalid"
                render action: "edit"
                return
              end
          else
            @campaign.rewards.create title: reward['title'],
                                     image_url: reward['image_url'],
                                     description: reward['description'],
                                     delivery_date: reward['delivery_date'],
                                     number: reward['number'].to_i,
                                     price: reward['price'].to_f,
                                     collect_shipping_flag: reward['collect_shipping_flag'],
                                     include_claimed: reward['include_claimed']
          end
        end
      end
    end

    if !@campaign.valid?
      flash.now[:error] = @campaign.errors.full_messages.join(', ')
      render action: "edit"
      return
    end

    # Set the campaign user id
     ct_user_id = @campaign.production_flag ? @settings.ct_production_admin_id : @settings.ct_sandbox_admin_id

    #if campaign has been promoted to production, delete all sandbox payments
    if @campaign.production_flag && @campaign.production_flag_changed?
      @campaign.payments.destroy_all
    end

    # calculate the goal amount (in case of a tilt by orders campaign)
    @campaign.set_goal
    logger.info "LOG STMT 1"
    # Update the corresponding campaign on the Crowdtilt API
    # If it fails, echo the error message sent by the API back to the user
    # If successful, save the campaign
    begin
      campaign = {
        title: @campaign.name,
        tilt_amount: (@campaign.goal_dollars*100).to_i,
        expiration_date: @campaign.expiration_date,
        billing_statement_text: @settings.billing_statement_text
      }
      logger.info "LOG STMT 2"
      # If the campaign has been promoted to production, create a new campaign on the Crowtilt API
      #if @campaign.production_flag && @campaign.production_flag_changed?
       # campaign[:user_id] = ct_user_id
        #Crowdtilt.production(@settings)
        #response = Crowdtilt.post('/campaigns', {campaign: campaign})
      #else
       # @campaign.production_flag ? Crowdtilt.production(@settings) : Crowdtilt.sandbox
       # response = Crowdtilt.put('/campaigns/' + @campaign.ct_campaign_id, {campaign: campaign})
      #end
    rescue => exception
      flash.now[:error] = exception.to_s
      render action: "edit" and return
    else
      #@campaign.update_api_data(response['campaign'])
      @campaign.save
      redirect_to campaign_home_url(@campaign), :flash => { :success => "Campaign updated!" } and return
    end
  end

  def payments
#     @campaign = Campaign.find(params[:id])
#     page = params[:page] || 1
#
#     #Check if the user is searching for a certain payment_id
#     if params.has_key?(:payment_id) && !params[:payment_id].blank?
#       begin
#         response = Crowdtilt.get('/campaigns/' + @campaign.ct_campaign_id + '/payments/' + params[:payment_id])
#       rescue => exception
#         #This means the payment_id wasn't found, so go ahead and grab all payments

app/controllers/api/v0/campaigns_controller.rb
class Api::V0::CampaignsController < Api::V0::BaseController
  def show
    render json: Campaign.find(params[:id])
  end
end

app/helpers/admin/campaigns_helper.rb
module Admin::CampaignsHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper

  def short_price(price, currency_symbol='', precision=nil)
    precision ||= (price*100%100==0.0 ? 0 : 2)
    "#{currency_symbol}#{number_with_precision(price, delimiter: ",", precision: precision)}"
  end
end

app/views/campaigns/checkout_amount.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
  <title>CysticLife Donation</title>
  <head>
    	<!-- Facebook Pixel Code -->
	<script>
		!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
		n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
		n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
		t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
		document,'script','//connect.facebook.net/en_US/fbevents.js');

		fbq('init', '<%= @campaign.video_embed_id %>');
		fbq('track', "PageView");
		fbq('track', "InitiateCheckout");
	</script>
	<noscript>
		<img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=<%= @campaign.video_embed_id %>&ev=PageView&noscript=1"/>
	</noscript>
	<!-- End Facebook Pixel Code -->

	<script type="text/javascript">
	function PopIt() {
		$('#exitModel').modal();                      // initialized with defaults
		$('#exitModel').modal({ keyboard: false });  // initialized with no keyboard
		$('#exitModel').modal('show');
		window.onbeforeunload = unPopIt;
		return "Your feedback is very important and, it takes just a minute. Please let us know your reason for not donating. Also, did you know that the minimum donation is $10?";
	}
	function unPopIt() {
		
	}
	window.onbeforeunload = PopIt;
 
	<% if local_assigns[:admin].nil? %>
	<% flash.to_hash().slice(:info).each do |key, value| %>
	<% if !value.blank? %>
		window.onbeforeunload = unPopIt;
	<% end %>
	<% end %>
	<% end %>
	
	
	var memoryLabel = "In memory of: ";
  function edValueKeyPress()
    {
        var s1 = $('#donormemory').val();
	$("#inmemoryValue").text(memoryLabel+s1);    
    }
</script>
    
  </head>
<div id="checkout">
  <div class="container content_box clearfix">
    <div class="main_content">
      <h3><a href="/web/<%= @campaign.facebook_title.downcase %>/pub?name=<%= @campaign.facebook_title %>&campaign=<%= @campaign.name.downcase.tr(' ', '_') unless @campaign.nil? %>&sr=<%= params[:sr]%>"><%= @campaign.name %></a></h3>

      <!-- <h3><a href="<%= campaign_home_path(@campaign) %>"><%= @campaign.name %></a></h3> -->

      <div class="checkout_block">
        <form accept-charset="UTF-8" action="<%= checkout_payment_path(@campaign, :sr => params[:sr]) %>" method="GET" id="amount_form">

          <% if @campaign.payment_type == 'fixed' %>

            <div class="quantity_input">
              <div class="donation_heading">
                <div style="float: right"><i class="icon icon-lock" data-placement="top"></i></div>
                <h4 class="amount_header"><strong> Select Donation Level:</strong></h4><br>
              </div>
              
              <% if @amountArray.nil?  %>
                  <div class="payment_div">
                    <input type="radio" name="quantity" class="payment_radio" id="quantity" value=<%= short_price((@campaign.fixed_payment_amount )) %> %>
                    <label class="payment_label">Donate <%= short_price((@campaign.fixed_payment_amount ), '$', 0) %></label>
                  </div><br>
                  <div class="payment_div">
                    <input type="radio" name="quantity" class="payment_radio" id="quantity" value=<%= short_price((@campaign.fixed_payment_amount * 2 )) %> %>
                    <label class="payment_label">Donate <%= short_price((@campaign.fixed_payment_amount * 2 ), '$', 0) %></label>
                  </div><br>
                  <div class="payment_div">
                    <input type="radio" name="quantity" class="payment_radio" id="quantity" value=<%= short_price((@campaign.fixed_payment_amount * 3 )) %> %>
                    <label class="payment_label">Donate <%= short_price((@campaign.fixed_payment_amount * 3 ), '$', 0) %></label>
                  </div><br>

               <% else %>
                  <% @amountArray.each do |amount_item| %>
                    <div class="payment_div">
                      <input type="radio" name="quantity" class="payment_radio" id="quantity" value=<%= short_price(amount_item) %> %>
                      <label class="payment_label">Donate <%= short_price(amount_item, '$', 0) %></label>
                    </div><br>
                  <% end %>

              <% end %> 
              <div class="payment_div">
                <input type="radio" name="quantity" class="payment_radio_other" id="quantity" value=1 %>
                <label class="payment_label">Other $</label>
                <!-- <input id="amount_other" disabled=<%= @quantity == 4? '':'disabled' %> placeholder= "Minimum <%= short_price((@campaign.fixed_payment_amount ), '$', 0) %>"  type="text" class="payment_text"  name="amount_other" /> -->
                <input id="amount_other" disabled=<%= @quantity == 4? '':'disabled' %>"  type="text" class="payment_text"  name="amount_other" />
              </div><br>
              
	      <div class="donation_heading" style="height: auto !important;">
                <div style="float: right"><i class="icon icon-question-sign show_tooltip" data-placement="top" data-title="This dedication will be displayed in our donor honor roll"></i></div>
		<label><strong>Optionally you can dedicate this donation to a loved one</strong></label>
              </div>

		<div class="donor_payment_div">
		  <input type="radio" name="memory" class="memory_radio" id="memory" onclick="inMemoryRadioClick()" value=0 checked %>
		  <label style="display: inline!important;"><strong>In memory of</strong></label><br>
		  <input type="radio" name="memory" class="memory_radio" id="memory" onclick="inHonorRadioClick()" value=1 %>
		  <label style="display: inline!important;"><strong>In honor of</strong></label>
		  <input id="donormemory" style="margin-top: 5px;" placeholder="Name of your loved one" name="donormemory" type="text" maxlength="50" onKeyPress="edValueKeyPress()" onKeyUp="edValueKeyPress()" class="paymentconfirm_text inspectletIgnore"><br>
		  <label id="inmemoryValue">In memory of:</label>
                </div>

	      
            </div>

            <input id="amount" type="hidden" name="amount" value="<%= number_with_precision(@campaign.fixed_payment_amount, precision: 2) %>" data-original="<%= number_with_precision(@campaign.fixed_payment_amount, precision: 2) %>"/>

          <% else %>

            <div class="amount_section">
            <h4 class="amount_header">Please enter an amount: </h4>
            <br/>
            <div class="amount_input" style="position:relative">
              <input id="amount" type="text" name="amount" value="<%= number_with_precision(@reward.price, precision: 2) if @reward %>"/>&nbsp;&nbsp;
              <span style="position:absolute">$</span>
            </div>
            <span class="minimum">Minimum is <%= short_price(@campaign.min_payment_amount, '$', 2) %></span>
            <label class="error hide"></label>
            </div>
            <input id="quantity" type="hidden" name="quantity" value="1"/>

          <% end %>
          <input id="sr" type="hidden" name="sr" value="<%= params[:sr]%>"/>

          <% if @campaign.rewards? %>
            <div id="reward_select" data-reference="<%= @campaign.reward_reference %>">
            <h4>Select your <%= @campaign.reward_reference %>: </h4>
            <ul>
              <li class="reward_option active <%= raw('hide') if @reward %> clearfix" data-id="0" data-price="<%= number_with_precision(@campaign.min_payment_amount, precision: 2) %>">
                  <input class="reward_input" type="radio" name="reward" value="0">
                  <label class="price"></label>
                  <div class="reward_description">
                    <p class="title">No <%= @campaign.reward_reference %></p>
                  </div>
                  <a class="reward_edit" href="#" style="display:none">edit</a>
              </li>
              <% @campaign.rewards.order("price ASC").each do |reward| %>
              <% if reward.visible? %>
                <li class="reward_option <%= raw('active') unless reward.sold_out? %> <%= ((@reward.id == reward.id) ? raw('selected') : raw('hide')) if @reward %> clearfix" data-id="<%= reward.id %>" data-price="<%= number_with_precision(reward.price, precision: 2) %>">
                  <input class="reward_input" type="radio" name="reward" value="<%= reward.id %>" <%= raw('disabled') if reward.sold_out? %><%= raw('checked="checked"') if @reward && @reward.id == reward.id %>>
                  <label class="price"><%= short_price(reward.price, '$') %> +</label>
                  <div class="reward_description">
                    <p class="title"><%= reward.title %></p>
                    <p class="claimed">
                      <%= reward.payments.successful.count %> <%= "of #{reward.number}" unless reward.unlimited? %> claimed
                      <% if reward.sold_out? %> (All gone!) <% end %>
                    </p>
                    <p class="description"><%= reward.description %></p>
                    <p class="delivery">Estimated Delivery: <%= reward.delivery_date %></p>
                  </div>
                  <a class="reward_edit" href="#" style="<%= 'display:none' unless @reward && @reward.id == reward.id %>">edit</a>
                </li>
              <% end %>
              <% end %>
            </ul>
            </div>
          <% end %>

          <div class="submit_div"><p class="submit_align" ><button type="submit" class="btn" id="continue_to_checkout">    Donate    </button>
          <!-- <%= link_to_function '<button type="button" class="btn">Back</button>'.html_safe , "history.back()" %> --> </p></div>

          <p style="font-size: 13px; margin-top: 20px">All donations are fully tax-deductible to fullest extent permitted by law.</p>

        </form>
      </div>
    </div>

    <div class="checkout_sidebar">
      <div class="custom_content">
        <%= raw(@campaign.checkout_sidebar_content) %>
      </div>
    </div>
    <div class="checkout_bottombar">
      <div class="custom_content">
        <%= raw(@campaign.checkout_sidebar_content) %>
      </div>
    </div>

  </div>

  
  
  
<div class="modal hide fade mobile_model" id="faqmodel">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">x</a>
    <h3>FAQ Content</h3>
  </div>
  <div class="modal-body">
    <iframe class="faq_content" id="faq_iframe"></iframe>
  </div>
</div>

<div class="modal hide fade mobile_model1" id="exitModel">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">x</a>
    <h3>Feedback</h3>
  </div>
  <div class="modal-body">
<form accept-charset="UTF-8" action="<%= send_feedback_path %>" method="post" id="feedback_form">
    	<div>
<div id="feedback_error" style="color: rgb(255,0,0)"></div>
    <table>
	<tboby>
		<tr style="padding: 5px">
		<td style="padding: 5px">
			<input type="radio" name="choice" class="exitModel_radio" onclick="radioClick()" id="quantity" value=101 %>
		</td>
		<td style="padding: 5px">
			<label class="exitModel_label">I would like lower payment choices (less than $25)</label>
		</td>	
		</tr>
		<tr style="padding: 5px">
		<td style="padding: 5px">
			<input type="radio" name="choice" class="exitModel_radio" onclick="radioClick()" id="quantity" value=102 %>
		</td>
		<td style="padding: 5px">
			<label class="exitModel_label">The sweepstake offers are unattractive</label>
		</td>	
		</tr>
		<tr style="padding: 5px">
		<td style="padding: 5px">
			<input type="radio" name="choice" class="exitModel_radio" onclick="radioClick()" id="quantity" value=103 %>
		</td>
		<td style="padding: 5px">
			<label class="exitModel_label">I feel payment maybe insecure</label>
		</td>	
		</tr>
		<tr style="padding: 5px">
		<td style="padding: 5px">
			<input type="radio" name="choice" class="exitModel_radio" onclick="otherRadioClick()" id="quantity" value=104 %>
		</td>
		<td style="padding: 5px">
			<label class="exitModel_label">Other reason</label>
		</td>	
		</tr>
		<tr style="padding: 5px">
		<td style="padding: 5px">
		</td>
		<td style="padding: 5px; width: 100%; ">
			<textarea id="feedback" name="feedback" rows="4" style="width: 96%; display: none;"></textarea>
		</td>	
		</tr>
	</tboby>
    </table>
    

	<div class="modal-footer">
	<button type="button" class="btn popup_submit" id="close-popup" onclick="stayBack()">I changed my mind, I will make a donation</button>
	<button type="submit" class="btn popup_submit show_loader" data-loader="feedback_form" id="submit-feed-back">Submit Feedback</button>
	<!-- <%= submit_tag "Submit Feedback", data: { disable_with: "Please wait.." } %>-->
	<!-- <%= button_to_function 'I changed my mind I will make a donation', 'stayBack()' %>-->
	<!-- <%= button_to_function 'No thanks, please close page', 'closeWondow()' %> -->
	</div>
        </form>
	</div>

  </div>

</div>


  
  
</div>